const animals = [
    { name: "lion", habitat: "land", fact: "Lions are the only cats that live in groups, called prides.", 
        fact2: "A lion's roar can be heard up to 5 miles away!" },
    { name: "tiger", habitat: "land", fact: "Tigers have unique stripe patterns, like human fingerprints.", 
        fact2: "Tigers are the largest wild cats in the world." },
    { name: "elephant", habitat: "land", fact: "Elephants are the largest land animals on Earth.", 
        fact2: "Elephants use their trunks for breathing, smelling, touching, and grasping." },
    { name: "giraffe", habitat: "land", fact: "Giraffes have the longest necks of any land mammal.", 
        fact2: "A giraffe's tongue can be up to 21 inches long!" },
    { name: "kangaroo", habitat: "land", fact: "Kangaroos are the only large animals that hop as their primary means of locomotion.", 
        fact2: "Baby kangaroos are called joeys." },
    { name: "panda", habitat: "land", fact: "Pandas eat almost exclusively bamboo.", 
        fact2: "Pandas have a special thumb-like structure on their paws to help them grasp bamboo." },
    { name: "gorilla", habitat: "land", fact: "Gorillas are the largest primates in the world.", 
        fact2: "Gorillas are highly intelligent and can use tools." },
    { name: "monkey", habitat: "land", fact: "There are over 260 different species of monkeys.", 
        fact2: "Some monkeys have prehensile tails that they can use like a fifth limb." },
    { name: "hippopotamus", habitat: "land/water", fact: "Hippos can hold their breath underwater for up to 5 minutes.", 
        fact2: "Hippos are surprisingly fast and can outrun humans on land." },
    { name: "bear", habitat: "land", fact: "Bears are omnivores and eat both plants and animals.", 
        fact2: "Polar bears have black skin under their white fur to help them absorb heat." },
    { name: "zebra", habitat: "land", fact: "Zebras have unique stripe patterns, which may help them confuse predators.", 
        fact2: "Zebras are social animals and live in herds." },
    { name: "raccoon", habitat: "land", fact: "Raccoons are known for their mask-like facial markings.", 
        fact2: "Raccoons have very sensitive paws that they use to feel for food in the dark." },
    { name: "squirrel", habitat: "land", fact: "Squirrels can jump up to 20 times their body length.", 
        fact2: "Squirrels bury nuts in the fall to eat during the winter." },
    { name: "deer", habitat: "land", fact: "Male deer have antlers that they shed and regrow each year.", 
        fact2: "Deer are herbivores and eat a variety of plants." },
    { name: "fox", habitat: "land", fact: "Foxes are known for their cunning and intelligence.", 
        fact2: "Foxes are solitary hunters, but they form pairs during the breeding season." },
    { name: "wolf", habitat: "land", fact: "Wolves live in packs, with a strict social hierarchy.", 
        fact2: "Wolves communicate through howls, barks, and body language." },
    { name: "leopard", habitat: "land", fact: "Leopards are excellent climbers and can drag prey up trees.", 
        fact2: "Leopards are solitary animals and come together only for mating." },
    { name: "cheetah", habitat: "land", fact: "Cheetahs are the fastest land animals, capable of reaching speeds up to 70 mph.", 
        fact2: "Cheetahs have a distinctive tear-shaped marking running from the corner of their eye down their cheek." },
    { name: "jaguar", habitat: "land", fact: "Jaguars are the largest cats in the Americas.", 
        fact2: "Jaguars have the strongest bite force of any big cat, relative to their size." },
    { name: "puma", habitat: "land", fact: "Pumas are also known as cougars or mountain lions.", 
        fact2: "Pumas can leap up to 18 feet high and 40 feet horizontally." },
    { name: "otter", habitat: "water", fact: "Otters are playful animals and often slide on their bellies for fun.", 
        fact2: "Otters have dense fur that helps keep them warm in cold water." },
    { name: "seal", habitat: "water", fact: "Seals are excellent swimmers and can dive deep underwater.", 
        fact2: "Seals have thick blubber to insulate them from the cold." },
    { name: "whale", habitat: "water", fact: "Whales are the largest animals on Earth.", 
        fact2: "Blue whales are the largest animals that have ever lived, even bigger than dinosaurs." },
    { name: "dolphin", habitat: "water", fact: "Dolphins are highly intelligent and social animals.", 
        fact2: "Dolphins use echolocation to find food and navigate." },
    { name: "shark", habitat: "water", fact: "Sharks have a skeleton made of cartilage, not bone.", 
        fact2: "Sharks have multiple rows of teeth that are constantly being replaced." },
    { name: "pigeon", habitat: "air", fact: "Pigeons are found in cities all over the world.", 
        fact2: "Pigeons have an excellent sense of direction and can find their way home from long distances." },
    { name: "parrot", habitat: "air", fact: "Parrots are known for their ability to mimic human speech.", 
        fact2: "The African Grey Parrot is considered one of the most intelligent bird species." },
    { name: "eagle", habitat: "air", fact: "Eagles have powerful talons and sharp beaks for hunting prey.", 
        fact2: "The Bald Eagle is the national bird of the United States." },
    { name: "woodpecker", habitat: "air", fact: "Woodpeckers use their strong beaks to drill holes in trees for nesting and finding food.", 
        fact2: "Woodpeckers have a special skull structure that protects their brains from the impact of pecking." },
    { name: "crow", habitat: "air", fact: "Crows are highly intelligent birds and can solve complex problems.", 
        fact2: "Crows are known to hold funerals for their dead." }
];

export { animals };